function varargout=F_yamada_T(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:9);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',6);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('F_yamada_T_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = F_yamada_T_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_yamada_T_rhs_0
%    [OUT1,OUT2,OUT3] = F_yamada_T_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Aug-2024 11:56:42

out1 = -in4.*in8.*in9.*(in1-in5+in1.*in3);
if nargout > 1
    out2 = -in4.*in8.*in9.*(in2-in6+in2.*in3.*in7);
end
if nargout > 2
    out3 = -in3.*in8.*in9.*(-in1+in2+1.0);
end
end


function [out1,out2,out3] = F_yamada_T_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_yamada_T_rhs_1
%    [OUT1,OUT2,OUT3] = F_yamada_T_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Aug-2024 11:56:42

t2 = in1.*in3;
t3 = in2.*in3.*in7;
t4 = -in1;
t5 = -in5;
t6 = -in6;
t7 = in2+t4+1.0;
t8 = in1+t2+t5;
out1 = -in4.*in8.*in18.*t8-in4.*in9.*in17.*t8-in8.*in9.*in13.*t8-in4.*in8.*in9.*(in10-in14+in1.*in12+in3.*in10);
if nargout > 1
    t9 = in2+t3+t6;
    out2 = -in4.*in8.*in9.*(in11-in15+in2.*in3.*in16+in2.*in7.*in12+in3.*in7.*in11)-in4.*in8.*in18.*t9-in4.*in9.*in17.*t9-in8.*in9.*in13.*t9;
end
if nargout > 2
    out3 = -in3.*in8.*in18.*t7-in3.*in9.*in17.*t7-in8.*in9.*in12.*t7+in3.*in8.*in9.*(in10-in11);
end
end


function [out1,out2,out3] = F_yamada_T_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_yamada_T_rhs_2
%    [OUT1,OUT2,OUT3] = F_yamada_T_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Aug-2024 11:56:42

t2 = in1.*in3;
t3 = in1.*in12;
t4 = in3.*in10;
t5 = in2.*in3.*in7;
t6 = in2.*in3.*in16;
t7 = in2.*in7.*in12;
t8 = in3.*in7.*in11;
t9 = -in1;
t10 = -in5;
t11 = -in6;
t12 = -in11;
t13 = -in14;
t14 = -in15;
t15 = in10+t12;
t16 = in2+t9+1.0;
t17 = in1+t2+t10;
t18 = in2+t5+t11;
t19 = in10+t3+t4+t13;
out1 = in4.*in8.*in18.*t19.*-2.0-in4.*in9.*in17.*t19.*2.0-in8.*in9.*in13.*t19.*2.0-in4.*in17.*in18.*t17.*2.0-in8.*in13.*in18.*t17.*2.0-in9.*in13.*in17.*t17.*2.0-in4.*in8.*in9.*in10.*in12.*2.0;
if nargout > 1
    t20 = in11+t6+t7+t8+t14;
    out2 = in4.*in8.*in18.*t20.*-2.0-in4.*in9.*in17.*t20.*2.0-in8.*in9.*in13.*t20.*2.0-in4.*in17.*in18.*t18.*2.0-in8.*in13.*in18.*t18.*2.0-in9.*in13.*in17.*t18.*2.0-in4.*in8.*in9.*(in2.*in12.*in16.*2.0+in3.*in11.*in16.*2.0+in7.*in11.*in12.*2.0);
end
if nargout > 2
    out3 = in3.*in8.*in18.*t15.*2.0+in3.*in9.*in17.*t15.*2.0+in8.*in9.*in12.*t15.*2.0-in3.*in17.*in18.*t16.*2.0-in8.*in12.*in18.*t16.*2.0-in9.*in12.*in17.*t16.*2.0;
end
end

