function varargout=F_bcs_PR(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=7;
   return
  case 'argrange'
   varargout{1}=struct('u',1:17);
   return
  case 'argsize'
   varargout{1}=struct('u',17);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=7;
order=varargin{1};
f=str2func(sprintf('F_bcs_PR_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6,out7] = F_bcs_PR_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_bcs_PR_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7] = F_bcs_PR_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:56

out1 = in1-in10;
if nargout > 1
    out2 = in2-in11;
end
if nargout > 2
    out3 = in3-in12;
end
if nargout > 3
    out4 = in4-in7;
end
if nargout > 4
    out5 = in5-in8;
end
if nargout > 5
    out6 = in6-in9;
end
if nargout > 6
    out7 = -in13.*(in1-in14+in1.*in3);
end
end


function [out1,out2,out3,out4,out5,out6,out7] = F_bcs_PR_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_bcs_PR_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7] = F_bcs_PR_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:56

out1 = in18-in27;
if nargout > 1
    out2 = in19-in28;
end
if nargout > 2
    out3 = in20-in29;
end
if nargout > 3
    out4 = in21-in24;
end
if nargout > 4
    out5 = in22-in25;
end
if nargout > 5
    out6 = in23-in26;
end
if nargout > 6
    out7 = -in30.*(in1-in14+in1.*in3)-in13.*(in18-in31+in1.*in20+in3.*in18);
end
end


function [out1,out2,out3,out4,out5,out6,out7] = F_bcs_PR_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_bcs_PR_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7] = F_bcs_PR_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:56

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = 0.0;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = in30.*(in18-in31+in1.*in20+in3.*in18).*-2.0-in13.*in18.*in20.*2.0;
end
end

