function varargout=F_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:8);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',5);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('F_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = F_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_seg2_rhs_0
%    [OUT1,OUT2,OUT3] = F_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:55

t2 = in8-1.0;
out1 = in4.*t2.*(in1-in5+in1.*in3);
if nargout > 1
    out2 = in4.*t2.*(in2-in6+in2.*in3.*in7);
end
if nargout > 2
    out3 = in3.*t2.*(-in1+in2+1.0);
end
end


function [out1,out2,out3] = F_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_seg2_rhs_1
%    [OUT1,OUT2,OUT3] = F_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:55

t2 = in1.*in3;
t3 = in2.*in3.*in7;
t4 = -in1;
t5 = -in5;
t6 = -in6;
t7 = in8-1.0;
t8 = in2+t4+1.0;
t9 = in1+t2+t5;
out1 = in4.*t7.*(in9-in13+in1.*in11+in3.*in9)+in4.*in16.*t9+in12.*t7.*t9;
if nargout > 1
    t10 = in2+t3+t6;
    out2 = in4.*t7.*(in10-in14+in2.*in3.*in15+in2.*in7.*in11+in3.*in7.*in10)+in4.*in16.*t10+in12.*t7.*t10;
end
if nargout > 2
    out3 = in3.*in16.*t8+in11.*t7.*t8-in3.*t7.*(in9-in10);
end
end


function [out1,out2,out3] = F_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_seg2_rhs_2
%    [OUT1,OUT2,OUT3] = F_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 12:32:55

t2 = in1.*in11;
t3 = in3.*in9;
t4 = in2.*in3.*in15;
t5 = in2.*in7.*in11;
t6 = in3.*in7.*in10;
t7 = -in10;
t8 = -in13;
t9 = -in14;
t10 = in8-1.0;
t11 = in9+t7;
t12 = in9+t2+t3+t8;
out1 = in4.*in16.*t12.*2.0+in12.*t10.*t12.*2.0+in12.*in16.*(in1-in5+in1.*in3).*2.0+in4.*in9.*in11.*t10.*2.0;
if nargout > 1
    t13 = in10+t4+t5+t6+t9;
    out2 = in12.*in16.*(in2-in6+in2.*in3.*in7).*2.0+in4.*t10.*(in2.*in11.*in15.*2.0+in3.*in10.*in15.*2.0+in7.*in10.*in11.*2.0)+in4.*in16.*t13.*2.0+in12.*t10.*t13.*2.0;
end
if nargout > 2
    out3 = in3.*in16.*t11.*-2.0-in11.*t10.*t11.*2.0+in11.*in16.*(-in1+in2+1.0).*2.0;
end
end

