function varargout=F_floquet(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=6;
   return
  case 'argrange'
   varargout{1}=struct('x',1:6,'p',7:12);
   return
  case 'argsize'
   varargout{1}=struct('x',6,'p',6);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=6;
order=varargin{1};
f=str2func(sprintf('F_floquet_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6] = F_floquet_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24)
%F_floquet_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_floquet_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    10-Jul-2025 20:36:36

out1 = -in7.*(in1-in8+in1.*in3);
if nargout > 1
    out2 = -in7.*(in2-in9+in2.*in3.*in10);
end
if nargout > 2
    t2 = in3.*in6;
    t3 = -in1;
    t4 = in2+t3+1.0;
    out3 = -in3.*t4;
end
if nargout > 3
    out4 = -t2+in4.*in7.*(in3+1.0);
end
if nargout > 4
    out5 = t2+in5.*in7.*(in3.*in10+1.0);
end
if nargout > 5
    out6 = in6.*t4+in1.*in4.*in7+in2.*in5.*in7.*in10;
end
end


function [out1,out2,out3,out4,out5,out6] = F_floquet_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24)
%F_floquet_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_floquet_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    10-Jul-2025 20:36:37

out1 = -in19.*(in1-in8+in1.*in3)-in7.*(in13-in20+in1.*in15+in3.*in13);
if nargout > 1
    t2 = in3.*in10;
    out2 = -in19.*(in2-in9+in2.*t2)-in7.*(in14-in21+in14.*t2+in2.*in3.*in22+in2.*in10.*in15);
end
if nargout > 2
    t3 = in3.*in18;
    t4 = in6.*in15;
    t5 = in3+1.0;
    t6 = -in1;
    t7 = -in14;
    t8 = t2+1.0;
    t9 = in13+t7;
    t10 = in2+t6+1.0;
    out3 = in3.*t9-in15.*t10;
end
if nargout > 3
    out4 = -t3-t4+in4.*in7.*in15+in4.*in19.*t5+in7.*in16.*t5;
end
if nargout > 4
    out5 = t3+t4+in5.*in19.*t8+in7.*in17.*t8+in5.*in7.*(in3.*in22+in10.*in15);
end
if nargout > 5
    out6 = -in6.*t9+in18.*t10+in1.*in4.*in19+in1.*in7.*in16+in4.*in7.*in13+in2.*in5.*in7.*in22+in2.*in5.*in10.*in19+in2.*in7.*in10.*in17+in5.*in7.*in10.*in14;
end
end


function [out1,out2,out3,out4,out5,out6] = F_floquet_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24)
%F_floquet_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_floquet_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    10-Jul-2025 20:36:37

out1 = in19.*(in13-in20+in1.*in15+in3.*in13).*-2.0-in7.*in13.*in15.*2.0;
if nargout > 1
    t2 = in3.*in22;
    t3 = in10.*in15;
    out2 = -in7.*(in14.*t2.*2.0+in14.*t3.*2.0+in2.*in15.*in22.*2.0)-in19.*(in14-in21+in2.*t2+in2.*t3+in3.*in10.*in14).*2.0;
end
if nargout > 2
    t4 = in15.*in18.*2.0;
    t5 = -in14;
    t6 = in13+t5;
    out3 = in15.*t6.*2.0;
end
if nargout > 3
    out4 = -t4+in4.*in15.*in19.*2.0+in7.*in15.*in16.*2.0+in16.*in19.*(in3+1.0).*2.0;
end
if nargout > 4
    t7 = t2+t3;
    out5 = t4+in5.*in19.*t7.*2.0+in7.*in17.*t7.*2.0+in17.*in19.*(in3.*in10+1.0).*2.0+in5.*in7.*in15.*in22.*2.0;
end
if nargout > 5
    out6 = in18.*t6.*-2.0+in1.*in16.*in19.*2.0+in4.*in13.*in19.*2.0+in7.*in13.*in16.*2.0+in2.*in5.*in19.*in22.*2.0+in2.*in7.*in17.*in22.*2.0+in2.*in10.*in17.*in19.*2.0+in5.*in7.*in14.*in22.*2.0+in5.*in10.*in14.*in19.*2.0+in7.*in10.*in14.*in17.*2.0;
end
end

