function varargout=F_seg3(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:15);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',12);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('F_seg3_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = F_seg3_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg3_rhs_0
%    [OUT1,OUT2,OUT3] = F_seg3_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Jul-2025 11:09:36

t2 = in9-1.0;
out1 = in4.*t2.*(in1-in5+in1.*in3);
if nargout > 1
    out2 = in4.*t2.*(in2-in6+in2.*in3.*in7);
end
if nargout > 2
    out3 = in3.*t2.*(-in1+in2+1.0);
end
end


function [out1,out2,out3] = F_seg3_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg3_rhs_1
%    [OUT1,OUT2,OUT3] = F_seg3_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Jul-2025 11:09:36

t2 = in1.*in3;
t3 = in2.*in3.*in7;
t4 = -in1;
t5 = -in5;
t6 = -in6;
t7 = in9-1.0;
t8 = in2+t4+1.0;
t9 = in1+t2+t5;
out1 = in4.*t7.*(in16-in20+in1.*in18+in3.*in16)+in4.*in24.*t9+in19.*t7.*t9;
if nargout > 1
    t10 = in2+t3+t6;
    out2 = in4.*t7.*(in17-in21+in2.*in3.*in22+in2.*in7.*in18+in3.*in7.*in17)+in4.*in24.*t10+in19.*t7.*t10;
end
if nargout > 2
    out3 = in3.*in24.*t8+in18.*t7.*t8-in3.*t7.*(in16-in17);
end
end


function [out1,out2,out3] = F_seg3_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg3_rhs_2
%    [OUT1,OUT2,OUT3] = F_seg3_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Jul-2025 11:09:36

t2 = in1.*in18;
t3 = in3.*in16;
t4 = in2.*in3.*in22;
t5 = in2.*in7.*in18;
t6 = in3.*in7.*in17;
t7 = -in17;
t8 = -in20;
t9 = -in21;
t10 = in9-1.0;
t11 = in16+t7;
t12 = in16+t2+t3+t8;
out1 = in4.*in24.*t12.*2.0+in19.*t10.*t12.*2.0+in19.*in24.*(in1-in5+in1.*in3).*2.0+in4.*in16.*in18.*t10.*2.0;
if nargout > 1
    t13 = in17+t4+t5+t6+t9;
    out2 = in19.*in24.*(in2-in6+in2.*in3.*in7).*2.0+in4.*t10.*(in2.*in18.*in22.*2.0+in3.*in17.*in22.*2.0+in7.*in17.*in18.*2.0)+in4.*in24.*t13.*2.0+in19.*t10.*t13.*2.0;
end
if nargout > 2
    out3 = in3.*in24.*t11.*-2.0-in18.*t10.*t11.*2.0+in18.*in24.*(-in1+in2+1.0).*2.0;
end
end

