function varargout=F_bcs_initial(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=6;
   return
  case 'argrange'
   varargout{1}=struct('u',1:21);
   return
  case 'argsize'
   varargout{1}=struct('u',21);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=6;
order=varargin{1};
f=str2func(sprintf('F_bcs_initial_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6] = F_bcs_initial_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42)
%F_bcs_initial_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_bcs_initial_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Aug-2024 16:33:37

t2 = cos(in21);
t3 = sin(in21);
t4 = -in7;
out1 = in1+t4-in10.*in19;
if nargout > 1
    t5 = -in8;
    out2 = in2+t5-in11.*in19;
end
if nargout > 2
    t6 = -in9;
    out3 = in3+t6-in12.*in19;
end
if nargout > 3
    out4 = in4+t4-in20.*(in13.*t2+in16.*t3);
end
if nargout > 4
    out5 = in5+t5-in20.*(in14.*t2+in17.*t3);
end
if nargout > 5
    out6 = in6+t6-in20.*(in15.*t2+in18.*t3);
end
end


function [out1,out2,out3,out4,out5,out6] = F_bcs_initial_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42)
%F_bcs_initial_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_bcs_initial_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Aug-2024 16:33:37

t2 = cos(in21);
t3 = sin(in21);
t4 = -in28;
out1 = in22+t4-in10.*in40-in19.*in31;
if nargout > 1
    t5 = -in29;
    out2 = in23+t5-in11.*in40-in19.*in32;
end
if nargout > 2
    t6 = -in30;
    out3 = in24+t6-in12.*in40-in19.*in33;
end
if nargout > 3
    out4 = in25+t4-in41.*(in13.*t2+in16.*t3)-in20.*(in34.*t2+in37.*t3-in13.*in42.*t3+in16.*in42.*t2);
end
if nargout > 4
    out5 = in26+t5-in41.*(in14.*t2+in17.*t3)-in20.*(in35.*t2+in38.*t3-in14.*in42.*t3+in17.*in42.*t2);
end
if nargout > 5
    out6 = in27+t6-in41.*(in15.*t2+in18.*t3)-in20.*(in36.*t2+in39.*t3-in15.*in42.*t3+in18.*in42.*t2);
end
end


function [out1,out2,out3,out4,out5,out6] = F_bcs_initial_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42)
%F_bcs_initial_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_bcs_initial_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Aug-2024 16:33:37

out1 = in31.*in40.*-2.0;
if nargout > 1
    out2 = in32.*in40.*-2.0;
end
if nargout > 2
    out3 = in33.*in40.*-2.0;
end
if nargout > 3
    t2 = cos(in21);
    t3 = sin(in21);
    t4 = in42.^2;
    out4 = in20.*(in34.*in42.*t3.*2.0-in37.*in42.*t2.*2.0+in13.*t2.*t4+in16.*t3.*t4)-in41.*(in34.*t2+in37.*t3-in13.*in42.*t3+in16.*in42.*t2).*2.0;
end
if nargout > 4
    out5 = in20.*(in35.*in42.*t3.*2.0-in38.*in42.*t2.*2.0+in14.*t2.*t4+in17.*t3.*t4)-in41.*(in35.*t2+in38.*t3-in14.*in42.*t3+in17.*in42.*t2).*2.0;
end
if nargout > 5
    out6 = in20.*(in36.*in42.*t3.*2.0-in39.*in42.*t2.*2.0+in15.*t2.*t4+in18.*t3.*t4)-in41.*(in36.*t2+in39.*t3-in15.*in42.*t3+in18.*in42.*t2).*2.0;
end
end

