function varargout=F_bcs_final(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('u',1:9);
   return
  case 'argsize'
   varargout{1}=struct('u',9);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_bcs_final_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_bcs_final_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_bcs_final_rhs_0
%    [OUT1,OUT2] = F_bcs_final_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2024 11:51:50

t2 = -in9;
out1 = in3+t2;
if nargout > 1
    out2 = in6+t2;
end
end


function [out1,out2] = F_bcs_final_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_bcs_final_rhs_1
%    [OUT1,OUT2] = F_bcs_final_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2024 11:51:50

t2 = -in18;
out1 = in12+t2;
if nargout > 1
    out2 = in15+t2;
end
end


function [out1,out2] = F_bcs_final_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%F_bcs_final_rhs_2
%    [OUT1,OUT2] = F_bcs_final_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2024 11:51:50

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
end

